# name: OIDC WhoAmI
# on:
#   workflow_dispatch:
# permissions:
#   id-token: write
#   contents: read
# jobs:
#   whoami:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: arn:aws:iam::ACCOUNT_ID:role/GitHubActionsDeployRole   # <-- replace
#           aws-region: us-east-1
#       - run: aws sts get-caller-identity